# Configuration file for AppVeyor CI
configuration: Release

platform: x86

cache: C:\Deps

nuget:
  account_feed: true

before_build:
- ps: >-
    if (!(Test-Path -Path "C:\Deps\gtk")) {
        Start-FileDownload "http://win32builder.gnome.org/gtk+-bundle_3.6.4-20130921_win32.zip" -FileName gtk.zip
        7z x -oC:\Deps\gtk gtk.zip | Out-Null
    }

    $env:Path += ";C:\Deps\gtk\bin"

    nuget restore

build:
  project: PasteSharp.sln
  publish_nuget: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal

after_build:
- ps: >-
    bin\Release\PasteSharp.exe --help
    bin\Release\PasteSharp.exe --version
